title: Pycado v0.00001
icon: resources/pycado.png

menus:
  file:
    name: "&File"
    # items
    new-file:
      name: New File
      icon: resources/document-new.png
      shortcut: Ctrl+N
      tip: Create a new file
      
    open-file:
      name: Open
      icon: resources/document-open.png
      shortcut: Ctrl+O
      tip: Open a file
      
    save:
      name: Save
      icon: resources/document-save.png
      shortcut: Ctrl+S
      tip: Save current file
      
    save-as:  
      name: Save As
      icon: resources/document-save-as.png
      shortcut: F12
      tip: Save current file as...
      
    quit:
      name: Quit
      icon: resources/system-log-out.png
      shortcut: Ctrl+Q
      tip: Quit Pycado